name: need test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check diff count
        id: check_bump
        run: echo "::set-output name=count::$(git diff main | grep hoge.txt | wc -l)"
