name: diff test

on:
  push:
    branches:
      - "feature/**"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Git Status
        run: git status

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Git Status
        run: git status

      - name: Git branch
        run: git branch

      - name: Check diff count
        id: check_bump
        run: echo "::set-output name=count::$(git diff origin/main origin/${GITHUB_HEAD_REF} | grep hoge.txt | wc -l)"

      - name: Output
        run: echo ${{ steps.check_bump.outputs.count }}

      - name: Check diff
        run: |
          MAIN=$(git rev-parse main)
          git diff $MAIN | grep hoge.txt | wc -l
