name: diff test

on:
  push:
    branches:
      - "feature/**"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch main
        run: |
          git fetch origin main --depth=1
          git switch -c main origin/main
          git switch ${GITHUB_REF#refs/heads/}

      - name: Git Status
        run: git status

      - name: Git branch
        run: git branch

      - name: Git diff
        run: git diff main

      - name: Git diff
        run: git diff main ${GITHUB_REF#refs/heads/}

      - name: Check diff count
        id: check_bump
        run: echo "::set-output name=count::$(git diff main | grep hoge.txt | wc -l)"

      - name: Output
        run: echo ${{ steps.check_bump.outputs.count }}
