name: diff test

on:
  push:
    branches:
      - "feature/**"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout -b main
          git checkout ${GITHUB_REF#refs/heads/}

      - name: Git Status
        run: git status

      - name: Git branch
        run: git branch

      - name: Check diff count
        id: check_bump
        run: echo "::set-output name=count::$(git diff main | grep hoge.txt | wc -l)"

      - name: Output
        run: echo ${{ steps.check_bump.outputs.count }}
