name: need test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step_output.outputs.count }}
    steps:
      - name: step
        run: echo "run job1 ğŸƒâ€â™‚ï¸"

      - name: Output
        id: step_output
        run: echo "::set-output name=count::1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.count == 0 }}
    steps:
      - name: step
        run: echo "run job2 ğŸƒâ€â™€ï¸"

      - name: needs output
        run: echo ${{ needs.job1.outputs.count }}
