name: need test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    if: 1 != 1
    steps:
      - id: step1
        run: echo "run job1 ğŸƒâ€â™‚ï¸"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - id: step1
        run: echo "run job2 ğŸƒâ€â™€ï¸"
